-- Pocket — proactive AI insights.
-- One LLM-generated, number-grounded observation per user per day, surfaced on
-- Home. Generated by the generate-insights edge function (client on Home open +
-- daily pg_cron). RLS-scoped to the owner.

create table public.insights (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  insight_text text not null,
  insight_type text not null check (insight_type in (
    'budget_velocity', 'trend_change', 'positive',
    'spending_pattern', 'forecast', 'splitwise'
  )),
  related_category text check (
    related_category is null or related_category in
    ('Food', 'Transport', 'Shopping', 'Entertainment', 'Other')
  ),
  created_at timestamptz not null default now(),
  dismissed boolean not null default false
);

create index insights_user_created_idx on public.insights (user_id, created_at desc);

alter table public.insights enable row level security;

create policy "insights owner full access"
  on public.insights for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
